/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AirplaneSystem;


import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class BookingTicketGUI extends javax.swing.JFrame {

    /**
     * Creates new form BookingTicketGUI
     */
    public BookingTicketGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Title = new javax.swing.JLabel();
        jLabel_TotalPassenger = new javax.swing.JLabel();
        jLabel_P_Name = new javax.swing.JLabel();
        jLabel_P_Age = new javax.swing.JLabel();
        jLabel_Destination = new javax.swing.JLabel();
        jLabel_TravelType = new javax.swing.JLabel();
        jLabel_AirplaneType = new javax.swing.JLabel();
        jLabel_AirplaneCode = new javax.swing.JLabel();
        jLabel_FlightClass = new javax.swing.JLabel();
        jLabel_Seat = new javax.swing.JLabel();
        jLabel_DateTravel = new javax.swing.JLabel();
        jLabel_DateReturn = new javax.swing.JLabel();
        jLabel_Luggage = new javax.swing.JLabel();
        jLabel_OKU = new javax.swing.JLabel();
        jLabel_Vaccinated = new javax.swing.JLabel();
        jLabel_VaccineType = new javax.swing.JLabel();
        jLabel_FirstDose = new javax.swing.JLabel();
        jLabel_SecondDose = new javax.swing.JLabel();
        jLabel_C19Result = new javax.swing.JLabel();
        jTextField_totalPassenger = new javax.swing.JTextField();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField_totalPassenger1 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextField_totalPassenger2 = new javax.swing.JTextField();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jTextField_totalPassenger3 = new javax.swing.JTextField();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel_VaccineType1 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jTextField_totalPassenger4 = new javax.swing.JTextField();
        jTextField_totalPassenger6 = new javax.swing.JTextField();
        jTextField_totalPassenger7 = new javax.swing.JTextField();
        jTextField_totalPassenger5 = new javax.swing.JTextField();
        jTextField_totalPassenger8 = new javax.swing.JTextField();
        jTextField_totalPassenger9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Title.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Title.setText("BOOKING TICKET");
        getContentPane().add(jLabel_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel_TotalPassenger.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_TotalPassenger.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_TotalPassenger.setText("Total Passenger");
        getContentPane().add(jLabel_TotalPassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel_P_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_P_Name.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_P_Name.setText("Name");
        getContentPane().add(jLabel_P_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel_P_Age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_P_Age.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_P_Age.setText("Age");
        getContentPane().add(jLabel_P_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel_Destination.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Destination.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Destination.setText("Destination");
        getContentPane().add(jLabel_Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));

        jLabel_TravelType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_TravelType.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_TravelType.setText("Travel Type");
        getContentPane().add(jLabel_TravelType, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        jLabel_AirplaneType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_AirplaneType.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_AirplaneType.setText("Airplane Type");
        getContentPane().add(jLabel_AirplaneType, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        jLabel_AirplaneCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_AirplaneCode.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_AirplaneCode.setText("Airplane Code [1]/[2]");
        getContentPane().add(jLabel_AirplaneCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, 20));

        jLabel_FlightClass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_FlightClass.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_FlightClass.setText("Flight Class Type");
        getContentPane().add(jLabel_FlightClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, -1, -1));

        jLabel_Seat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Seat.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Seat.setText("Choose Seat Num");
        getContentPane().add(jLabel_Seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, -1, -1));

        jLabel_DateTravel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_DateTravel.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_DateTravel.setText("Date Travel");
        getContentPane().add(jLabel_DateTravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        jLabel_DateReturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_DateReturn.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_DateReturn.setText("Date Return");
        getContentPane().add(jLabel_DateReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, -1, -1));

        jLabel_Luggage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Luggage.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Luggage.setText("Total Luggage");
        getContentPane().add(jLabel_Luggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, -1, -1));

        jLabel_OKU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_OKU.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_OKU.setText("OKU");
        getContentPane().add(jLabel_OKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, -1, -1));

        jLabel_Vaccinated.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Vaccinated.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Vaccinated.setText("Vaccinated");
        getContentPane().add(jLabel_Vaccinated, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, -1, -1));

        jLabel_VaccineType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_VaccineType.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel_VaccineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, -1));

        jLabel_FirstDose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_FirstDose.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_FirstDose.setText("1st Dose Date");
        getContentPane().add(jLabel_FirstDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, -1, -1));

        jLabel_SecondDose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_SecondDose.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_SecondDose.setText("2nd Dose Date");
        getContentPane().add(jLabel_SecondDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, -1, -1));

        jLabel_C19Result.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_C19Result.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_C19Result.setText("Covid-19 Result");
        getContentPane().add(jLabel_C19Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, -1, -1));

        jTextField_totalPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalPassengerActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_totalPassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 96, 33));
        getContentPane().add(jTextField_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 294, 33));
        getContentPane().add(jTextField_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 98, 33));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("One Way Trip");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setText("Round Trip");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("[1]Kedah    \t[2]Selangor \n[3]Penang  \t[4]Perak \n[5]Pahang\t[6]Johor \n[7]Melaka \t[8]Kelantan/Terengganu \n[9]Sarawak \t[10]Sabah");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 300, 120));

        jTextField_totalPassenger1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalPassenger1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_totalPassenger1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 140, 33));

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setText("AirAsia - [1]AA052 [2]AA889");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton4.setText("Mas - [1]MAS55 [2]MAS78");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton5.setText("Malindo - [1]MD460 [2]MD157");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, -1));

        jTextField_totalPassenger2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalPassenger2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_totalPassenger2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 78, 33));

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton6.setText("Business - Seat (1-100)");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, -1, -1));

        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton7.setText("First - Seat(1-40)");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, -1, -1));

        jRadioButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton8.setText("Economy");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 100, -1));

        jTextField_totalPassenger3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalPassenger3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_totalPassenger3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 73, 33));

        jRadioButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton9.setText("Yes");
        getContentPane().add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, -1, -1));

        jRadioButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton10.setText("No");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 290, -1, -1));

        jRadioButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton11.setText("Yes");
        getContentPane().add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 330, -1, -1));

        jRadioButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton12.setText("No");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 330, -1, -1));

        jLabel_VaccineType1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_VaccineType1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_VaccineType1.setText("Vaccine Type");
        getContentPane().add(jLabel_VaccineType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, -1, -1));

        jRadioButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton13.setText("Sinovac");
        getContentPane().add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 370, -1, -1));

        jRadioButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton14.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton14.setText("PFizer");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, -1, -1));

        jRadioButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton15.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton15.setText("Astrazeneca");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, -1, -1));

        jTextField_totalPassenger4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalPassenger4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_totalPassenger4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 78, 33));

        jTextField_totalPassenger6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalPassenger6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_totalPassenger6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, 140, 33));

        jTextField_totalPassenger7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalPassenger7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_totalPassenger7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 480, 140, 33));

        jTextField_totalPassenger5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalPassenger5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_totalPassenger5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, 140, 33));

        jTextField_totalPassenger8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalPassenger8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_totalPassenger8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 140, 33));

        jTextField_totalPassenger9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_totalPassenger9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_totalPassenger9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 78, 33));

        jButton2.setText("Next");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 630, 90, 30));

        jButton3.setText("Submit");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 630, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_totalPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalPassengerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalPassengerActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField_totalPassenger1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalPassenger1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalPassenger1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTextField_totalPassenger2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalPassenger2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalPassenger2ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jTextField_totalPassenger3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalPassenger3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalPassenger3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jTextField_totalPassenger4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalPassenger4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalPassenger4ActionPerformed

    private void jTextField_totalPassenger6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalPassenger6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalPassenger6ActionPerformed

    private void jTextField_totalPassenger7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalPassenger7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalPassenger7ActionPerformed

    private void jTextField_totalPassenger5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalPassenger5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalPassenger5ActionPerformed

    private void jTextField_totalPassenger8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalPassenger8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalPassenger8ActionPerformed

    private void jTextField_totalPassenger9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_totalPassenger9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_totalPassenger9ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingTicketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingTicketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingTicketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingTicketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingTicketGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel_AirplaneCode;
    private javax.swing.JLabel jLabel_AirplaneType;
    private javax.swing.JLabel jLabel_C19Result;
    private javax.swing.JLabel jLabel_DateReturn;
    private javax.swing.JLabel jLabel_DateTravel;
    private javax.swing.JLabel jLabel_Destination;
    private javax.swing.JLabel jLabel_FirstDose;
    private javax.swing.JLabel jLabel_FlightClass;
    private javax.swing.JLabel jLabel_Luggage;
    private javax.swing.JLabel jLabel_OKU;
    private javax.swing.JLabel jLabel_P_Age;
    private javax.swing.JLabel jLabel_P_Name;
    private javax.swing.JLabel jLabel_Seat;
    private javax.swing.JLabel jLabel_SecondDose;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_TotalPassenger;
    private javax.swing.JLabel jLabel_TravelType;
    private javax.swing.JLabel jLabel_Vaccinated;
    private javax.swing.JLabel jLabel_VaccineType;
    private javax.swing.JLabel jLabel_VaccineType1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_totalPassenger;
    private javax.swing.JTextField jTextField_totalPassenger1;
    private javax.swing.JTextField jTextField_totalPassenger2;
    private javax.swing.JTextField jTextField_totalPassenger3;
    private javax.swing.JTextField jTextField_totalPassenger4;
    private javax.swing.JTextField jTextField_totalPassenger5;
    private javax.swing.JTextField jTextField_totalPassenger6;
    private javax.swing.JTextField jTextField_totalPassenger7;
    private javax.swing.JTextField jTextField_totalPassenger8;
    private javax.swing.JTextField jTextField_totalPassenger9;
    // End of variables declaration//GEN-END:variables
}
