/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AirplaneSystem;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class RegistrationGUI extends javax.swing.JFrame {
    /**
     * Creates new form RegistrationGUI
     */
    public RegistrationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registration_Label = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_IC = new javax.swing.JTextField();
        jTextField_PhoneNum = new javax.swing.JTextField();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Age = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_IC = new javax.swing.JLabel();
        jLabel_PhoneNum = new javax.swing.JLabel();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Registration = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel_Pass = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registration_Label.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Registration_Label.setForeground(new java.awt.Color(0, 0, 0));
        Registration_Label.setText("REGISTRATION");
        getContentPane().add(Registration_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 28, -1, -1));

        jTextField_Name.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Name.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 110, 393, -1));

        jTextField_Age.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Age.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeActionPerformed(evt);
            }
        });
        jTextField_Age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_AgeKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 151, 393, -1));

        jTextField_Email.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Email.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 192, 393, -1));

        jTextField_IC.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_IC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_IC.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_IC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ICActionPerformed(evt);
            }
        });
        jTextField_IC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ICKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_IC, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 233, 393, -1));

        jTextField_PhoneNum.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_PhoneNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_PhoneNum.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_PhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneNumActionPerformed(evt);
            }
        });
        jTextField_PhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhoneNumKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_PhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 274, 393, -1));

        jLabel_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Name.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Name.setText("NAME");
        getContentPane().add(jLabel_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 110, -1, 23));

        jLabel_Age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Age.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Age.setText("AGE");
        getContentPane().add(jLabel_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 151, -1, 23));

        jLabel_Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Email.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Email.setText("EMAIL");
        getContentPane().add(jLabel_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 192, -1, 23));

        jLabel_IC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_IC.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_IC.setText("IC NUMBER");
        getContentPane().add(jLabel_IC, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 233, -1, 23));

        jLabel_PhoneNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_PhoneNum.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_PhoneNum.setText("PHONE NUMBER");
        getContentPane().add(jLabel_PhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 274, -1, 23));

        jButton_Cancel.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirplaneSystem/icons8-cross-mark-25.png"))); // NOI18N
        jButton_Cancel.setText("CANCEL");
        jButton_Cancel.setBorder(null);
        jButton_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CancelMouseExited(evt);
            }
        });
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 106, 33));

        jButton_Registration.setBackground(new java.awt.Color(255, 153, 153));
        jButton_Registration.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Registration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirplaneSystem/icons8-login-25.png"))); // NOI18N
        jButton_Registration.setText("REGISTER");
        jButton_Registration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_RegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_RegistrationMouseExited(evt);
            }
        });
        jButton_Registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrationActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 392, 533, 38));

        jPasswordField.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 315, 393, -1));

        jLabel_Pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Pass.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Pass.setText("PASSWORD");
        getContentPane().add(jLabel_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 315, -1, 23));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("Already have an Account? Login here!");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jTextField_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeActionPerformed

    private void jTextField_AgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AgeKeyTyped
        // TODO add your handling code here:
        //allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_AgeKeyTyped

    private void jTextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmailActionPerformed

    private void jTextField_ICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ICActionPerformed

    private void jTextField_ICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ICKeyTyped
        // TODO add your handling code here:
        //allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_ICKeyTyped

    private void jTextField_PhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneNumActionPerformed

    private void jTextField_PhoneNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneNumKeyTyped
        // TODO add your handling code here:
        //allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_PhoneNumKeyTyped

    private void jButton_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelMouseEntered
        // TODO add your handling code here:
        jButton_Cancel.setBackground(new Color(225,20,2));
    }//GEN-LAST:event_jButton_CancelMouseEntered

    private void jButton_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelMouseExited
        // TODO add your handling code here:
        jButton_Cancel.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_jButton_CancelMouseExited

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to CANCEL REGISTRATION", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_RegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegistrationMouseEntered
        // TODO add your handling code here:
        jButton_Registration.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_jButton_RegistrationMouseEntered

    private void jButton_RegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegistrationMouseExited
        // TODO add your handling code here:
        jButton_Registration.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_jButton_RegistrationMouseExited

    private void jButton_RegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrationActionPerformed
        // TODO add your handling code here:
        Person p = new Person(jTextField_Name.getText(),jTextField_Email.getText(),jTextField_IC.getText(),jTextField_PhoneNum.getText(),
                Integer.valueOf(jTextField_Age.getText()),String.valueOf(jPasswordField.getPassword()));
        
        /*if(name.trim().equals("") || age.trim().equals("") || Email.trim().equals("")|| icNum.trim().equals("")
                || phoneNum.trim().equals("") || pass1.trim().equals("")){
            JOptionPane.showMessageDialog(null, "One or More Fields are EMPTY", "Empty Fields", 2);
        }*/
            if(p.Register()){
                JOptionPane.showMessageDialog(rootPane, "Register Complete");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Register Failed");
            }
    }//GEN-LAST:event_jButton_RegistrationActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        LoginGUI lg = new LoginGUI();
        lg.setVisible(true);
        lg.pack();
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.black);
        jLabel9.setBorder(label_border);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        jLabel9.setBorder(null);
    }//GEN-LAST:event_jLabel9MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Registration_Label;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Registration;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Age;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_IC;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Pass;
    private javax.swing.JLabel jLabel_PhoneNum;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_IC;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_PhoneNum;
    // End of variables declaration//GEN-END:variables
}
