/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AirplaneSystem;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class RegistrationGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationGUI
     */
    public RegistrationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registration_Label = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_IC = new javax.swing.JTextField();
        jTextField_PhoneNum = new javax.swing.JTextField();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Age = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_IC = new javax.swing.JLabel();
        jLabel_PhoneNum = new javax.swing.JLabel();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Registration = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel_Pass = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Registration_Label.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Registration_Label.setForeground(new java.awt.Color(0, 0, 0));
        Registration_Label.setText("REGISTRATION");

        jTextField_Name.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Name.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });

        jTextField_Age.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Age.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeActionPerformed(evt);
            }
        });
        jTextField_Age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_AgeKeyTyped(evt);
            }
        });

        jTextField_Email.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Email.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmailActionPerformed(evt);
            }
        });

        jTextField_IC.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_IC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_IC.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_IC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ICActionPerformed(evt);
            }
        });
        jTextField_IC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ICKeyTyped(evt);
            }
        });

        jTextField_PhoneNum.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_PhoneNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_PhoneNum.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_PhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneNumActionPerformed(evt);
            }
        });
        jTextField_PhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhoneNumKeyTyped(evt);
            }
        });

        jLabel_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Name.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Name.setText("NAME");

        jLabel_Age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Age.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Age.setText("AGE");

        jLabel_Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Email.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Email.setText("EMAIL");

        jLabel_IC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_IC.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_IC.setText("IC NUMBER");

        jLabel_PhoneNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_PhoneNum.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_PhoneNum.setText("PHONE NUMBER");

        jButton_Cancel.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirplaneSystem/icons8-cross-mark-25.png"))); // NOI18N
        jButton_Cancel.setText("CANCEL");
        jButton_Cancel.setBorder(null);
        jButton_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CancelMouseExited(evt);
            }
        });
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jButton_Registration.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Registration.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Registration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirplaneSystem/icons8-login-25.png"))); // NOI18N
        jButton_Registration.setText("REGISTER");
        jButton_Registration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_RegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_RegistrationMouseExited(evt);
            }
        });
        jButton_Registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrationActionPerformed(evt);
            }
        });

        jPasswordField.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jLabel_Pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Pass.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Pass.setText("PASSWORD");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("Already have an Account? Login here!");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addComponent(Registration_Label))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_Name)
                            .addGap(122, 122, 122)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_Age)
                            .addGap(135, 135, 135)
                            .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_Email)
                            .addGap(118, 118, 118)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_IC)
                            .addGap(81, 81, 81)
                            .addComponent(jTextField_IC, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_PhoneNum)
                            .addGap(47, 47, 47)
                            .addComponent(jTextField_PhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_Pass)
                            .addGap(82, 82, 82)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jButton_Registration, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(187, 187, 187)
                            .addComponent(jLabel9))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(275, 275, 275)
                            .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Registration_Label)
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_IC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_IC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_PhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_PhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(54, 54, 54)
                    .addComponent(jButton_Registration, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(54, 54, 54)
                    .addComponent(jLabel9)
                    .addGap(18, 18, 18)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jTextField_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeActionPerformed

    private void jTextField_AgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AgeKeyTyped
        // TODO add your handling code here:
        //allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_AgeKeyTyped

    private void jTextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmailActionPerformed

    private void jTextField_ICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ICActionPerformed

    private void jTextField_ICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ICKeyTyped
        // TODO add your handling code here:
        //allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_ICKeyTyped

    private void jTextField_PhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneNumActionPerformed

    private void jTextField_PhoneNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneNumKeyTyped
        // TODO add your handling code here:
        //allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_PhoneNumKeyTyped

    private void jButton_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelMouseEntered
        // TODO add your handling code here:
        jButton_Cancel.setBackground(new Color(225,20,2));
    }//GEN-LAST:event_jButton_CancelMouseEntered

    private void jButton_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelMouseExited
        // TODO add your handling code here:
        jButton_Cancel.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_jButton_CancelMouseExited

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to CANCEL REGISTRATION", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_RegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegistrationMouseEntered
        // TODO add your handling code here:
        jButton_Registration.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_jButton_RegistrationMouseEntered

    private void jButton_RegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegistrationMouseExited
        // TODO add your handling code here:
        jButton_Registration.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_jButton_RegistrationMouseExited

    private void jButton_RegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrationActionPerformed
        // TODO add your handling code here:
        String name = jTextField_Name.getText();
        String age = jTextField_Age.getText();
        String Email = jTextField_Email.getText();
        String icNum = jTextField_IC.getText();
        String phoneNum = jTextField_PhoneNum.getText();
        String pass1 = String.valueOf(jPasswordField.getPassword());

        if(verifyField()){
            if(!checkAcc(name) && !checkEmail(Email)){
                PreparedStatement ps;
                String registerAccQuery = "INSERT INTO `accountregistration`(`Name`, `Age`, `Email`, `IC Number`, `Phone Number`, `Password`) VALUES (?,?,?,?,?,?)";

                try {
                    ps = Database.getConnection().prepareStatement(registerAccQuery);
                    ps.setString(1, name);
                    ps.setString(2,age);
                    ps.setString(3,Email);
                    ps.setString(4,icNum);
                    ps.setString(5,phoneNum);
                    ps.setString(6,pass1);

                    //ps.setNull(5,java.sql.Types.NULL);
                    if(ps.executeUpdate() != 0){
                        JOptionPane.showMessageDialog(null, "Your Account Has Been Created");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "ERROR: Check Your Information");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(RegistrationGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton_RegistrationActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        LoginGUI lg = new LoginGUI();
        lg.setVisible(true);
        lg.pack();
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.black);
        jLabel9.setBorder(label_border);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        jLabel9.setBorder(null);
    }//GEN-LAST:event_jLabel9MouseExited
    
    //create a funtion to verify the empty fields
    public boolean verifyField(){
        String name = jTextField_Name.getText();
        String age = jTextField_Age.getText();
        String Email = jTextField_Email.getText();
        String icNum = jTextField_IC.getText();
        String phoneNum = jTextField_PhoneNum.getText();
        String pass1 = String.valueOf(jPasswordField.getPassword());
        
        
        if(name.trim().equals("") || age.trim().equals("") || Email.trim().equals("")|| icNum.trim().equals("")
                || phoneNum.trim().equals("") || pass1.trim().equals("") || pass1.trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "One or More Fields are EMPTY", "Empty Fields", 2);
            return false;
        }
        //if everythign is okay
        else{
            return true;
        }
    }
    
    //create a unction to check if the acc already exists
    public boolean checkAcc(String name){
        PreparedStatement st;
        ResultSet rs;
        boolean name_exist = false;
        
        String query = "SELECT * FROM `accountregistration` WHERE (`Name` = ?)";
        
        try {
            st = Database.getConnection().prepareStatement(query);
            st.setString(1, name);
            rs = st.executeQuery();
            
            if(rs.next()){
                name_exist = true;
                JOptionPane.showMessageDialog(null, "You Already have an ACCOUNT", "Name Failed", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return name_exist;
    }
    
    //create a unction to check if the email already exists
    public boolean checkEmail(String email){
        PreparedStatement st;
        ResultSet rs;
        boolean email_exist = false;
        
        String query = "SELECT * FROM `accountregistration` WHERE (`Email` = ?)";
        
        try {
            st = Database.getConnection().prepareStatement(query);
            st.setString(1, email);
            rs = st.executeQuery();
            
            if(rs.next()){
                email_exist = true;
                JOptionPane.showMessageDialog(null, "You Already have an ACCOUNT", "Email Failed", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return email_exist;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Registration_Label;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Registration;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Age;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_IC;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Pass;
    private javax.swing.JLabel jLabel_PhoneNum;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_IC;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_PhoneNum;
    // End of variables declaration//GEN-END:variables
}
